name: CI
on:
  push:
  pull_request:
jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Repo structure sanity
        run: |
          test -f README.md
          test -d docs
          test -d src
          test -d tests
      - name: Spellcheck docs (basic)
        run: |
          grep -qi "vios" README.md
